### ISSUE TITLE
aliyun-oss-csharp-sdk 和 alibabacloud-oss-sdk 区别

### ISSUE THREAD

**Issue by sangeren** [aliyun/alibabacloud-oss-sdk#151]
这两个有什么不同吗，推荐用哪一个？

**Comment by JacksonTian** [comment]
Hi @sangeren 感谢您的关注。

aliyun-oss-csharp-sdk 和 当前这个仓库下的区别是，前者是通过 OSS API 文档编写的 SDK，各个语言各自实现的。

当前这个仓库是由元数据统一描述，然后各个语言统一生成的。
