### ISSUE TITLE
这里升级为什么要加  Tea::merge

### ISSUE THREAD

**Issue by xiongxinag** [aliyun/alibabacloud-oss-sdk#249]
报错位置:

 '/vendor/alibabacloud/tea/src/Tea.php -> 254',
 '/vendor/alibabacloud/tea-oss-sdk/src/OSS.php -> 7142',

'Severity: \'.Warning.\'  --> \'.array_merge() expects at least 1 parameter, 0 given. \' \'.src/Tea.php.\' \'.254

原代码
Utils::stringifyMapValue($request->header)
升级后报错代码
Utils::stringifyMapValue(Tea::merge($request->header))

问题 这里升级为什么要加  Tea::merge

**Comment by AxiosCros** [comment]
没有报错信息吗？

**Comment by AxiosCros** [comment]
Tea::merge 方法可以处理更多可能的情况，这里的 warning 是传入的 $request->header 应该为 null 值，稍后我会更新一个版本。

**Comment by AxiosCros** [comment]
已经提 [PR](https://github.com/aliyun/tea-php/pull/40) 了，合入需要一些时间。

**Comment by AxiosCros** [comment]
已发布 [tea-php 3.1.20](https://github.com/aliyun/tea-php/releases/tag/3.1.20) 版本
