### ISSUE TITLE
AlibabaCloud\Tea\OSSUtils\VerifyStream::read() 不支持最新依赖包

### ISSUE THREAD

**Issue by tinyu0** [aliyun/alibabacloud-oss-sdk#266]
错误内容：
Declaration of AlibabaCloud\Tea\OSSUtils\VerifyStream::read($length) must be compatible with GuzzleHttp\Psr7\Stream::read($length): string in /var/www/html/vendor/alibabacloud/tea-oss-utils/src/VerifyStream.php:49

问题：
"alibabacloud/viapi-utils" 依赖 "alibabacloud/tea-oss-utils": "^0.2.0",
"alibabacloud/tea-oss-utils": "0.2.2"  依赖 "alibabacloud/tea": "^3.0",
"alibabacloud/tea":"3.1.22" 依赖 "guzzlehttp/guzzle": "^6.3|^7.0"
"guzzlehttp/guzzle":"7.3.0" 依赖 "guzzlehttp/psr7": "^1.7 || ^2.0",
"guzzlehttp/psr7":"2.0.0" Stream::read() 定义 返回类型声明

"alibabacloud/tea-oss-utils" 包内的 AlibabaCloud\Tea\OSSUtils\VerifyStream::read() 没有 定义返回类型声明

**Comment by franklin87** [comment]
然后就没然后了？

**Comment by yndu13** [comment]
已支持，commit：https://github.com/aliyun/alibabacloud-oss-sdk/commit/7fc74f9fa2fe0f0203cc24e4db6612945d34bb6c
