### ISSUE TITLE
/src/ViapiUtils.php 的29行read方法会报错

### ISSUE THREAD

**Issue by zdx0823** [aliyun/alibabacloud-oss-sdk#270]
错误提示：
Declaration of AlibabaCloud\Tea\OSSUtils\VerifyStream::read($length) must be compatible with GuzzleHttp\Psr7\Stream::read($length): string

看了下是继承的Stream文件216行是强类型声明，在/src/ViapiUtils.php加上 :string 就好了

**Comment by franklin87** [comment]
> 错误提示： Declaration of AlibabaCloud\Tea\OSSUtils\VerifyStream::read($length) must be compatible with GuzzleHttp\Psr7\Stream::read($length): string
> 
> 看了下是继承的Stream文件216行是强类型声明，在/src/ViapiUtils.php加上 :string 就好了

我怎么是把 :string 删了就好了

**Comment by yndu13** [comment]
已支持，commit：https://github.com/aliyun/alibabacloud-oss-sdk/commit/7fc74f9fa2fe0f0203cc24e4db6612945d34bb6c
