### ISSUE TITLE
tea-oss-utils VerifyStream

### ISSUE THREAD

**Issue by LinXueYi** [aliyun/alibabacloud-oss-sdk#274]
### 项目依赖
- "alibabacloud/viapi-utils": "^0.1.3"
- "guzzlehttp/guzzle": "^7.0.1"

### 错误信息
Declaration of AlibabaCloud\\Tea\\OSSUtils\\VerifyStream::read($length) must be compatible with GuzzleHttp\\Psr7\\Stream::read($length): string

### 解决方法
`alibabacloud\tea-oss-utils\src\VerifyStream.php 修改 read 方法`

```php
public function read($length) : string
{
    $string = parent::read($length);
    if (!empty($string)) {
        $this->crcRead->append($string);
        $this->content .= $string;
    }

    return $string;
}
```

**Comment by yndu13** [comment]
已支持，commit：https://github.com/aliyun/alibabacloud-oss-sdk/commit/7fc74f9fa2fe0f0203cc24e4db6612945d34bb6c
